name: lint
on: [push, pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Lint
        uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: "./..."

      - name: Fmt
        uses: Jerome1337/gofmt-action@v1.0.2
        with:
          gofmt-path: "."

      - name: Golangci-lint
        uses: reviewdog/action-golangci-lint@v1
